### PR TITLE
Implement LeColor so that the a pixel is RGBA on all platforms

### PR DESCRIPTION
**Pull request by m0ppers**
WIP - do not merge yet (unless you know immediately how to fix it or you )

enabling SSE2 results in cyan 👎 

rest seems ok

with this change I see the same triangle problems that I have on the Amiga (let the cube rotate for a while - suddenly colors are off).

Will check if I can find out why it is broken and add to this pull request.

Todos:

- [x] Test UNIX
- [x] Test GCC
- [x] Fix triangle glitches
- [x] Fix SSE2

### CODE REVIEW

**Comment by Marzac** [comment]
Hi M0ppers.
I have had a short review of the code. Everything seems to be alright.
I have just one concerned, you have swapped the whole engine to work with RGBA values whereas 90% of the OS it supports work with ABGR values instead. Also WIN bitmaps (native format of picture representation in engine) are ABGR too.

I understand the little / big endian problematic but could the word be swapped just for big endian systems? Is there a performance problem?

**Comment by Marzac** [comment]
I have the engine integrated with a QT application now that also need AGBR values. 
And it does not make use of the window / draw classes (only renders to bitmap).
So it makes it incompatible now.

**Comment by m0ppers** [comment]
fix under way :) you are right

**Comment by m0ppers** [comment]
glitching finally fixed. ready when you are and you are fine with it?

as far as I know it should be possible to squash merge a pull request from the UI (so my commits appear as 1 commit in the main repo). I think that would make sense.

**Comment by Marzac** [comment]
Ok I merged with the main branch. Now I gonna be testing this with different projects.

**Comment by Marzac** [comment]
So it compiles and runs fine with VS 2017.

**Comment by Marzac** [comment]
I am now checking with mingw64.

**Comment by Marzac** [comment]
Currently checking:
- [ ] mingw64 IntRaster, no SIMD, win32
- [ ] mingw64 FloatRaster, no SIMD, win32
- [ ] mingw64 IntRaster, SSE, win32
- [ ] mingw64 FloatRaster, SSE, win32
- [ ] vs IntRaster, no SIMD, win32
- [ ] vs FloatRaster, no SIMD, win32
- [ ] vs IntRaster, SSE, win32
- [ ] vs FloatRaster, SSE, win32

**Comment by Marzac** [comment]
There is something weird though.
The executables are now mega fett 800kB instead of 150kB before, any idea?

**Comment by Marzac** [comment]
Any weird C++ feature that would require a load of runtime checks, tables or so?

**Pull request merged**
